"""ML Pipeline Configuration"""
import os

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DATA_DIR = os.path.join(BASE_DIR, "data")
MODEL_DIR = os.path.join(BASE_DIR, "models")
DB_PATH = os.path.join(DATA_DIR, "market_data.db")

# Dhan API
DHAN_BASE = "https://api.dhan.co/v2"
DHAN_TOKEN = os.environ.get("DHAN_ACCESS_TOKEN", "")
DHAN_CLIENT_ID = os.environ.get("DHAN_CLIENT_ID", "1105206730")

# Data collection
HISTORY_YEARS = 5
YAHOO_BATCH_SIZE = 50        # symbols per yfinance batch
YAHOO_RATE_DELAY = 0.5       # seconds between batches
DHAN_RATE_DELAY = 0.3        # seconds between Dhan API calls

# Feature engineering
RSI_PERIODS = [7, 14]
SMA_PERIODS = [5, 10, 20, 50, 100, 200]
EMA_PERIODS = [9, 21]
ATR_PERIOD = 14
BB_PERIOD = 20
MACD_FAST, MACD_SLOW, MACD_SIGNAL = 12, 26, 9

# Training
TRAIN_YEARS = 4              # years for training window
TEST_MONTHS = 1              # months per walk-forward step
MIN_SAMPLES = 100            # minimum samples to train
TARGET_HORIZON = 5           # predict N-day forward return
TARGET_THRESHOLD = 0.005     # 0.5% move = directional signal

# Model
XGBOOST_PARAMS = {
    "n_estimators": 500,
    "max_depth": 6,
    "learning_rate": 0.05,
    "subsample": 0.8,
    "colsample_bytree": 0.8,
    "min_child_weight": 5,
    "reg_alpha": 0.1,
    "reg_lambda": 1.0,
    "objective": "multi:softprob",
    "num_class": 3,           # LONG / NEUTRAL / SHORT
    "eval_metric": "mlogloss",
    "tree_method": "hist",
    "random_state": 42,
    "n_jobs": -1,
}

LIGHTGBM_PARAMS = {
    "n_estimators": 500,
    "max_depth": 6,
    "learning_rate": 0.05,
    "subsample": 0.8,
    "colsample_bytree": 0.8,
    "min_child_samples": 20,
    "reg_alpha": 0.1,
    "reg_lambda": 1.0,
    "objective": "multiclass",
    "num_class": 3,
    "metric": "multi_logloss",
    "random_state": 42,
    "n_jobs": -1,
    "verbose": -1,
}

# Prediction server
SERVER_HOST = "0.0.0.0"
SERVER_PORT = 5055

# F&O Stock list (symbol → Yahoo symbol)
FNO_INDICES = {
    "NIFTY": "^NSEI",
    "BANKNIFTY": "^NSEBANK",
    "FINNIFTY": "NIFTY_FIN_SERVICE.NS",
    "MIDCPNIFTY": "^NSMIDCP",
}

FNO_STOCKS = {
    "360ONE": "360ONE.NS", "ABB": "ABB.NS", "ABCAPITAL": "ABCAPITAL.NS",
    "ADANIENSOL": "ADANIENSOL.NS", "ADANIENT": "ADANIENT.NS", "ADANIGREEN": "ADANIGREEN.NS",
    "ADANIPORTS": "ADANIPORTS.NS", "ALKEM": "ALKEM.NS", "AMBER": "AMBER.NS",
    "AMBUJACEM": "AMBUJACEM.NS", "ANGELONE": "ANGELONE.NS", "APLAPOLLO": "APLAPOLLO.NS",
    "APOLLOHOSP": "APOLLOHOSP.NS", "ASHOKLEY": "ASHOKLEY.NS", "ASIANPAINT": "ASIANPAINT.NS",
    "ASTRAL": "ASTRAL.NS", "AUBANK": "AUBANK.NS", "AUROPHARMA": "AUROPHARMA.NS",
    "AXISBANK": "AXISBANK.NS", "BAJAJ-AUTO": "BAJAJ-AUTO.NS", "BAJAJFINSV": "BAJAJFINSV.NS",
    "BAJFINANCE": "BAJFINANCE.NS", "BANDHANBNK": "BANDHANBNK.NS", "BANKBARODA": "BANKBARODA.NS",
    "BANKINDIA": "BANKINDIA.NS", "BDL": "BDL.NS", "BEL": "BEL.NS",
    "BHARATFORG": "BHARATFORG.NS", "BHARTIARTL": "BHARTIARTL.NS", "BHEL": "BHEL.NS",
    "BIOCON": "BIOCON.NS", "BLUESTARCO": "BLUESTARCO.NS", "BOSCHLTD": "BOSCHLTD.NS",
    "BPCL": "BPCL.NS", "BRITANNIA": "BRITANNIA.NS", "BSE": "BSE.NS",
    "CAMS": "CAMS.NS", "CANBK": "CANBK.NS", "CDSL": "CDSL.NS",
    "CGPOWER": "CGPOWER.NS", "CHOLAFIN": "CHOLAFIN.NS", "CIPLA": "CIPLA.NS",
    "COALINDIA": "COALINDIA.NS", "COFORGE": "COFORGE.NS", "COLPAL": "COLPAL.NS",
    "CONCOR": "CONCOR.NS", "CROMPTON": "CROMPTON.NS", "CUMMINSIND": "CUMMINSIND.NS",
    "CYIENT": "CYIENT.NS", "DABUR": "DABUR.NS", "DALBHARAT": "DALBHARAT.NS",
    "DELHIVERY": "DELHIVERY.NS", "DIVISLAB": "DIVISLAB.NS", "DIXON": "DIXON.NS",
    "DLF": "DLF.NS", "DMART": "DMART.NS", "DRREDDY": "DRREDDY.NS",
    "EICHERMOT": "EICHERMOT.NS", "ETERNAL": "ETERNAL.NS", "EXIDEIND": "EXIDEIND.NS",
    "FEDERALBNK": "FEDERALBNK.NS", "FORTIS": "FORTIS.NS", "GAIL": "GAIL.NS",
    "GLENMARK": "GLENMARK.NS", "GMRAIRPORT": "GMRAIRPORT.NS", "GODREJCP": "GODREJCP.NS",
    "GODREJPROP": "GODREJPROP.NS", "GRASIM": "GRASIM.NS", "HAL": "HAL.NS",
    "HAVELLS": "HAVELLS.NS", "HCLTECH": "HCLTECH.NS", "HDFCAMC": "HDFCAMC.NS",
    "HDFCBANK": "HDFCBANK.NS", "HDFCLIFE": "HDFCLIFE.NS", "HEROMOTOCO": "HEROMOTOCO.NS",
    "HFCL": "HFCL.NS", "HINDALCO": "HINDALCO.NS", "HINDPETRO": "HINDPETRO.NS",
    "HINDUNILVR": "HINDUNILVR.NS", "HINDZINC": "HINDZINC.NS", "HUDCO": "HUDCO.NS",
    "ICICIBANK": "ICICIBANK.NS", "ICICIGI": "ICICIGI.NS", "ICICIPRULI": "ICICIPRULI.NS",
    "IDEA": "IDEA.NS", "IDFCFIRSTB": "IDFCFIRSTB.NS", "IEX": "IEX.NS",
    "IGL": "IGL.NS", "IIFL": "IIFL.NS", "INDHOTEL": "INDHOTEL.NS",
    "INDIANB": "INDIANB.NS", "INDIGO": "INDIGO.NS", "INDUSINDBK": "INDUSINDBK.NS",
    "INDUSTOWER": "INDUSTOWER.NS", "INFY": "INFY.NS", "INOXWIND": "INOXWIND.NS",
    "IOC": "IOC.NS", "IRCTC": "IRCTC.NS", "IREDA": "IREDA.NS",
    "IRFC": "IRFC.NS", "ITC": "ITC.NS", "JINDALSTEL": "JINDALSTEL.NS",
    "JIOFIN": "JIOFIN.NS", "JSWENERGY": "JSWENERGY.NS", "JSWSTEEL": "JSWSTEEL.NS",
    "JUBLFOOD": "JUBLFOOD.NS", "KALYANKJIL": "KALYANKJIL.NS", "KAYNES": "KAYNES.NS",
    "KEI": "KEI.NS", "KFINTECH": "KFINTECH.NS", "KOTAKBANK": "KOTAKBANK.NS",
    "KPITTECH": "KPITTECH.NS", "LAURUSLABS": "LAURUSLABS.NS", "LICHSGFIN": "LICHSGFIN.NS",
    "LICI": "LICI.NS", "LODHA": "LODHA.NS", "LT": "LT.NS",
    "LTF": "LTF.NS", "LTIM": "LTIM.NS", "LUPIN": "LUPIN.NS",
    "M&M": "M%26M.NS", "MANAPPURAM": "MANAPPURAM.NS", "MANKIND": "MANKIND.NS",
    "MARICO": "MARICO.NS", "MARUTI": "MARUTI.NS", "MAXHEALTH": "MAXHEALTH.NS",
    "MAZDOCK": "MAZDOCK.NS", "MCX": "MCX.NS", "MFSL": "MFSL.NS",
    "MOTHERSON": "MOTHERSON.NS", "MPHASIS": "MPHASIS.NS", "MUTHOOTFIN": "MUTHOOTFIN.NS",
    "NATIONALUM": "NATIONALUM.NS", "NAUKRI": "NAUKRI.NS", "NBCC": "NBCC.NS",
    "NCC": "NCC.NS", "NESTLEIND": "NESTLEIND.NS", "NHPC": "NHPC.NS",
    "NMDC": "NMDC.NS", "NTPC": "NTPC.NS", "NUVAMA": "NUVAMA.NS",
    "NYKAA": "NYKAA.NS", "OBEROIRLTY": "OBEROIRLTY.NS", "OFSS": "OFSS.NS",
    "OIL": "OIL.NS", "ONGC": "ONGC.NS", "PAGEIND": "PAGEIND.NS",
    "PATANJALI": "PATANJALI.NS", "PAYTM": "PAYTM.NS", "PERSISTENT": "PERSISTENT.NS",
    "PETRONET": "PETRONET.NS", "PFC": "PFC.NS", "PGEL": "PGEL.NS",
    "PHOENIXLTD": "PHOENIXLTD.NS", "PIDILITIND": "PIDILITIND.NS", "PIIND": "PIIND.NS",
    "PNB": "PNB.NS", "PNBHOUSING": "PNBHOUSING.NS", "POLICYBZR": "POLICYBZR.NS",
    "POLYCAB": "POLYCAB.NS", "POWERGRID": "POWERGRID.NS", "POWERINDIA": "POWERINDIA.NS",
    "PPLPHARMA": "PPLPHARMA.NS", "PRESTIGE": "PRESTIGE.NS", "RBLBANK": "RBLBANK.NS",
    "RECLTD": "RECLTD.NS", "RELIANCE": "RELIANCE.NS", "RVNL": "RVNL.NS",
    "SAIL": "SAIL.NS", "SAMMAANCAP": "SAMMAANCAP.NS", "SBICARD": "SBICARD.NS",
    "SBILIFE": "SBILIFE.NS", "SBIN": "SBIN.NS", "SHREECEM": "SHREECEM.NS",
    "SHRIRAMFIN": "SHRIRAMFIN.NS", "SIEMENS": "SIEMENS.NS", "SOLARINDS": "SOLARINDS.NS",
    "SONACOMS": "SONACOMS.NS", "SRF": "SRF.NS", "SUNPHARMA": "SUNPHARMA.NS",
    "SUPREMEIND": "SUPREMEIND.NS", "SUZLON": "SUZLON.NS", "SYNGENE": "SYNGENE.NS",
    "TATACONSUM": "TATACONSUM.NS", "TATAELXSI": "TATAELXSI.NS", "TATAMOTORS": "TATAMOTORS.NS",
    "TATAPOWER": "TATAPOWER.NS", "TATASTEEL": "TATASTEEL.NS", "TATATECH": "TATATECH.NS",
    "TCS": "TCS.NS", "TECHM": "TECHM.NS", "TIINDIA": "TIINDIA.NS",
    "TITAGARH": "TITAGARH.NS", "TITAN": "TITAN.NS", "TORNTPHARM": "TORNTPHARM.NS",
    "TORNTPOWER": "TORNTPOWER.NS", "TRENT": "TRENT.NS", "TVSMOTOR": "TVSMOTOR.NS",
    "ULTRACEMCO": "ULTRACEMCO.NS", "UNIONBANK": "UNIONBANK.NS", "UNITDSPR": "UNITDSPR.NS",
    "UNOMINDA": "UNOMINDA.NS", "UPL": "UPL.NS", "VBL": "VBL.NS",
    "VEDL": "VEDL.NS", "VOLTAS": "VOLTAS.NS", "WIPRO": "WIPRO.NS",
    "YESBANK": "YESBANK.NS", "ZYDUSLIFE": "ZYDUSLIFE.NS",
}

# Sector mapping for relative strength
SECTOR_MAP = {
    "BANKING": ["HDFCBANK", "ICICIBANK", "SBIN", "AXISBANK", "KOTAKBANK", "BANKBARODA", "PNB", "INDUSINDBK", "FEDERALBNK", "IDFCFIRSTB", "AUBANK", "BANDHANBNK", "CANBK", "INDIANB", "RBLBANK"],
    "IT": ["TCS", "INFY", "HCLTECH", "WIPRO", "TECHM", "LTIM", "MPHASIS", "COFORGE", "PERSISTENT", "KPITTECH", "CYIENT", "TATAELXSI"],
    "PHARMA": ["SUNPHARMA", "DRREDDY", "CIPLA", "DIVISLAB", "LUPIN", "AUROPHARMA", "BIOCON", "TORNTPHARM", "ALKEM", "GLENMARK", "MANKIND", "LAURUSLABS", "SYNGENE"],
    "AUTO": ["TATAMOTORS", "MARUTI", "BAJAJ-AUTO", "EICHERMOT", "HEROMOTOCO", "M&M", "TVSMOTOR", "ASHOKLEY", "BHARATFORG"],
    "ENERGY": ["RELIANCE", "ONGC", "BPCL", "IOC", "GAIL", "HINDPETRO", "PETRONET", "OIL", "NTPC", "POWERGRID", "TATAPOWER", "ADANIGREEN", "ADANIENSOL", "JSWENERGY", "NHPC", "COALINDIA"],
    "METALS": ["TATASTEEL", "JSWSTEEL", "HINDALCO", "VEDL", "SAIL", "JINDALSTEL", "NMDC", "NATIONALUM", "HINDZINC"],
    "FMCG": ["HINDUNILVR", "ITC", "NESTLEIND", "BRITANNIA", "DABUR", "MARICO", "COLPAL", "GODREJCP", "TATACONSUM", "VBL", "PATANJALI"],
    "REALTY": ["DLF", "GODREJPROP", "OBEROIRLTY", "PRESTIGE", "PHOENIXLTD", "LODHA"],
    "INFRA": ["LT", "ADANIENT", "ADANIPORTS", "CONCOR", "NCC", "NBCC", "RVNL"],
    "FINANCE": ["BAJFINANCE", "BAJAJFINSV", "CHOLAFIN", "SHRIRAMFIN", "MUTHOOTFIN", "MANAPPURAM", "LICHSGFIN", "PFC", "RECLTD", "HUDCO", "IRFC", "SBICARD", "HDFCLIFE", "SBILIFE", "ICICIPRULI", "ICICIGI", "LICI"],
}

ALL_SYMBOLS = {**FNO_INDICES, **FNO_STOCKS}
