// All 209 NSE F&O stocks + 5 indices with lot sizes
// Source: https://ournifty.com/stock-list-in-nse-fo-futures-and-options.html (Jan 2026)

export const FNO_INDICES: Record<string, { yahoo: string; lot: number; step: number }> = {
  "NIFTY": { yahoo: "%5ENSEI", lot: 25, step: 50 },
  "BANKNIFTY": { yahoo: "%5ENSEBANK", lot: 15, step: 100 },
  "FINNIFTY": { yahoo: "NIFTY_FIN_SERVICE.NS", lot: 60, step: 50 },
  "MIDCPNIFTY": { yahoo: "%5ENSMIDCP", lot: 120, step: 25 },
};

export const FNO_STOCKS: Record<string, { yahoo: string; lot: number }> = {
  "360ONE": { yahoo: "360ONE.NS", lot: 500 },
  "ABB": { yahoo: "ABB.NS", lot: 125 },
  "ABCAPITAL": { yahoo: "ABCAPITAL.NS", lot: 3100 },
  "ADANIENSOL": { yahoo: "ADANIENSOL.NS", lot: 675 },
  "ADANIENT": { yahoo: "ADANIENT.NS", lot: 300 },
  "ADANIGREEN": { yahoo: "ADANIGREEN.NS", lot: 600 },
  "ADANIPORTS": { yahoo: "ADANIPORTS.NS", lot: 475 },
  "ALKEM": { yahoo: "ALKEM.NS", lot: 125 },
  "AMBER": { yahoo: "AMBER.NS", lot: 100 },
  "AMBUJACEM": { yahoo: "AMBUJACEM.NS", lot: 1050 },
  "ANGELONE": { yahoo: "ANGELONE.NS", lot: 250 },
  "APLAPOLLO": { yahoo: "APLAPOLLO.NS", lot: 350 },
  "APOLLOHOSP": { yahoo: "APOLLOHOSP.NS", lot: 125 },
  "ASHOKLEY": { yahoo: "ASHOKLEY.NS", lot: 5000 },
  "ASIANPAINT": { yahoo: "ASIANPAINT.NS", lot: 250 },
  "ASTRAL": { yahoo: "ASTRAL.NS", lot: 425 },
  "AUBANK": { yahoo: "AUBANK.NS", lot: 1000 },
  "AUROPHARMA": { yahoo: "AUROPHARMA.NS", lot: 550 },
  "AXISBANK": { yahoo: "AXISBANK.NS", lot: 625 },
  "BAJAJ-AUTO": { yahoo: "BAJAJ-AUTO.NS", lot: 75 },
  "BAJAJFINSV": { yahoo: "BAJAJFINSV.NS", lot: 500 },
  "BAJFINANCE": { yahoo: "BAJFINANCE.NS", lot: 750 },
  "BANDHANBNK": { yahoo: "BANDHANBNK.NS", lot: 3600 },
  "BANKBARODA": { yahoo: "BANKBARODA.NS", lot: 2925 },
  "BANKINDIA": { yahoo: "BANKINDIA.NS", lot: 5200 },
  "BDL": { yahoo: "BDL.NS", lot: 325 },
  "BEL": { yahoo: "BEL.NS", lot: 2850 },
  "BHARATFORG": { yahoo: "BHARATFORG.NS", lot: 500 },
  "BHARTIARTL": { yahoo: "BHARTIARTL.NS", lot: 475 },
  "BHEL": { yahoo: "BHEL.NS", lot: 2625 },
  "BIOCON": { yahoo: "BIOCON.NS", lot: 2500 },
  "BLUESTARCO": { yahoo: "BLUESTARCO.NS", lot: 325 },
  "BOSCHLTD": { yahoo: "BOSCHLTD.NS", lot: 25 },
  "BPCL": { yahoo: "BPCL.NS", lot: 1975 },
  "BRITANNIA": { yahoo: "BRITANNIA.NS", lot: 125 },
  "BSE": { yahoo: "BSE.NS", lot: 375 },
  "CAMS": { yahoo: "CAMS.NS", lot: 150 },
  "CANBK": { yahoo: "CANBK.NS", lot: 6750 },
  "CDSL": { yahoo: "CDSL.NS", lot: 475 },
  "CGPOWER": { yahoo: "CGPOWER.NS", lot: 850 },
  "CHOLAFIN": { yahoo: "CHOLAFIN.NS", lot: 625 },
  "CIPLA": { yahoo: "CIPLA.NS", lot: 375 },
  "COALINDIA": { yahoo: "COALINDIA.NS", lot: 1350 },
  "COFORGE": { yahoo: "COFORGE.NS", lot: 375 },
  "COLPAL": { yahoo: "COLPAL.NS", lot: 225 },
  "CONCOR": { yahoo: "CONCOR.NS", lot: 1250 },
  "CROMPTON": { yahoo: "CROMPTON.NS", lot: 1800 },
  "CUMMINSIND": { yahoo: "CUMMINSIND.NS", lot: 200 },
  "CYIENT": { yahoo: "CYIENT.NS", lot: 425 },
  "DABUR": { yahoo: "DABUR.NS", lot: 1250 },
  "DALBHARAT": { yahoo: "DALBHARAT.NS", lot: 325 },
  "DELHIVERY": { yahoo: "DELHIVERY.NS", lot: 2075 },
  "DIVISLAB": { yahoo: "DIVISLAB.NS", lot: 100 },
  "DIXON": { yahoo: "DIXON.NS", lot: 50 },
  "DLF": { yahoo: "DLF.NS", lot: 825 },
  "DMART": { yahoo: "DMART.NS", lot: 150 },
  "DRREDDY": { yahoo: "DRREDDY.NS", lot: 625 },
  "EICHERMOT": { yahoo: "EICHERMOT.NS", lot: 175 },
  "ETERNAL": { yahoo: "ETERNAL.NS", lot: 2425 },
  "EXIDEIND": { yahoo: "EXIDEIND.NS", lot: 1800 },
  "FEDERALBNK": { yahoo: "FEDERALBNK.NS", lot: 5000 },
  "FORTIS": { yahoo: "FORTIS.NS", lot: 775 },
  "GAIL": { yahoo: "GAIL.NS", lot: 3150 },
  "GLENMARK": { yahoo: "GLENMARK.NS", lot: 375 },
  "GMRAIRPORT": { yahoo: "GMRAIRPORT.NS", lot: 6975 },
  "GODREJCP": { yahoo: "GODREJCP.NS", lot: 500 },
  "GODREJPROP": { yahoo: "GODREJPROP.NS", lot: 275 },
  "GRASIM": { yahoo: "GRASIM.NS", lot: 250 },
  "HAL": { yahoo: "HAL.NS", lot: 150 },
  "HAVELLS": { yahoo: "HAVELLS.NS", lot: 500 },
  "HCLTECH": { yahoo: "HCLTECH.NS", lot: 350 },
  "HDFCAMC": { yahoo: "HDFCAMC.NS", lot: 150 },
  "HDFCBANK": { yahoo: "HDFCBANK.NS", lot: 1100 },
  "HDFCLIFE": { yahoo: "HDFCLIFE.NS", lot: 1100 },
  "HEROMOTOCO": { yahoo: "HEROMOTOCO.NS", lot: 150 },
  "HFCL": { yahoo: "HFCL.NS", lot: 6450 },
  "HINDALCO": { yahoo: "HINDALCO.NS", lot: 1400 },
  "HINDPETRO": { yahoo: "HINDPETRO.NS", lot: 2025 },
  "HINDUNILVR": { yahoo: "HINDUNILVR.NS", lot: 300 },
  "HINDZINC": { yahoo: "HINDZINC.NS", lot: 1225 },
  "HUDCO": { yahoo: "HUDCO.NS", lot: 2775 },
  "ICICIBANK": { yahoo: "ICICIBANK.NS", lot: 700 },
  "ICICIGI": { yahoo: "ICICIGI.NS", lot: 325 },
  "ICICIPRULI": { yahoo: "ICICIPRULI.NS", lot: 925 },
  "IDEA": { yahoo: "IDEA.NS", lot: 71475 },
  "IDFCFIRSTB": { yahoo: "IDFCFIRSTB.NS", lot: 9275 },
  "IEX": { yahoo: "IEX.NS", lot: 3750 },
  "IGL": { yahoo: "IGL.NS", lot: 2750 },
  "IIFL": { yahoo: "IIFL.NS", lot: 1650 },
  "INDHOTEL": { yahoo: "INDHOTEL.NS", lot: 1000 },
  "INDIANB": { yahoo: "INDIANB.NS", lot: 1000 },
  "INDIGO": { yahoo: "INDIGO.NS", lot: 150 },
  "INDUSINDBK": { yahoo: "INDUSINDBK.NS", lot: 700 },
  "INDUSTOWER": { yahoo: "INDUSTOWER.NS", lot: 1700 },
  "INFY": { yahoo: "INFY.NS", lot: 400 },
  "INOXWIND": { yahoo: "INOXWIND.NS", lot: 3272 },
  "IOC": { yahoo: "IOC.NS", lot: 4875 },
  "IRCTC": { yahoo: "IRCTC.NS", lot: 875 },
  "IREDA": { yahoo: "IREDA.NS", lot: 3450 },
  "IRFC": { yahoo: "IRFC.NS", lot: 4250 },
  "ITC": { yahoo: "ITC.NS", lot: 1600 },
  "JINDALSTEL": { yahoo: "JINDALSTEL.NS", lot: 625 },
  "JIOFIN": { yahoo: "JIOFIN.NS", lot: 2350 },
  "JSWENERGY": { yahoo: "JSWENERGY.NS", lot: 1000 },
  "JSWSTEEL": { yahoo: "JSWSTEEL.NS", lot: 675 },
  "JUBLFOOD": { yahoo: "JUBLFOOD.NS", lot: 1250 },
  "KALYANKJIL": { yahoo: "KALYANKJIL.NS", lot: 1175 },
  "KAYNES": { yahoo: "KAYNES.NS", lot: 100 },
  "KEI": { yahoo: "KEI.NS", lot: 175 },
  "KFINTECH": { yahoo: "KFINTECH.NS", lot: 450 },
  "KOTAKBANK": { yahoo: "KOTAKBANK.NS", lot: 400 },
  "KPITTECH": { yahoo: "KPITTECH.NS", lot: 400 },
  "LAURUSLABS": { yahoo: "LAURUSLABS.NS", lot: 1700 },
  "LICHSGFIN": { yahoo: "LICHSGFIN.NS", lot: 1000 },
  "LICI": { yahoo: "LICI.NS", lot: 700 },
  "LODHA": { yahoo: "LODHA.NS", lot: 450 },
  "LT": { yahoo: "LT.NS", lot: 175 },
  "LTF": { yahoo: "LTF.NS", lot: 4462 },
  "LTIM": { yahoo: "LTIM.NS", lot: 150 },
  "LUPIN": { yahoo: "LUPIN.NS", lot: 425 },
  "M&M": { yahoo: "M%26M.NS", lot: 200 },
  "MANAPPURAM": { yahoo: "MANAPPURAM.NS", lot: 3000 },
  "MANKIND": { yahoo: "MANKIND.NS", lot: 225 },
  "MARICO": { yahoo: "MARICO.NS", lot: 1200 },
  "MARUTI": { yahoo: "MARUTI.NS", lot: 50 },
  "MAXHEALTH": { yahoo: "MAXHEALTH.NS", lot: 525 },
  "MAZDOCK": { yahoo: "MAZDOCK.NS", lot: 175 },
  "MCX": { yahoo: "MCX.NS", lot: 125 },
  "MFSL": { yahoo: "MFSL.NS", lot: 800 },
  "MOTHERSON": { yahoo: "MOTHERSON.NS", lot: 6150 },
  "MPHASIS": { yahoo: "MPHASIS.NS", lot: 275 },
  "MUTHOOTFIN": { yahoo: "MUTHOOTFIN.NS", lot: 275 },
  "NATIONALUM": { yahoo: "NATIONALUM.NS", lot: 3750 },
  "NAUKRI": { yahoo: "NAUKRI.NS", lot: 375 },
  "NBCC": { yahoo: "NBCC.NS", lot: 6500 },
  "NCC": { yahoo: "NCC.NS", lot: 2700 },
  "NESTLEIND": { yahoo: "NESTLEIND.NS", lot: 500 },
  "NHPC": { yahoo: "NHPC.NS", lot: 6400 },
  "NMDC": { yahoo: "NMDC.NS", lot: 13500 },
  "NTPC": { yahoo: "NTPC.NS", lot: 1500 },
  "NUVAMA": { yahoo: "NUVAMA.NS", lot: 75 },
  "NYKAA": { yahoo: "NYKAA.NS", lot: 3125 },
  "OBEROIRLTY": { yahoo: "OBEROIRLTY.NS", lot: 350 },
  "OFSS": { yahoo: "OFSS.NS", lot: 75 },
  "OIL": { yahoo: "OIL.NS", lot: 1400 },
  "ONGC": { yahoo: "ONGC.NS", lot: 2250 },
  "PAGEIND": { yahoo: "PAGEIND.NS", lot: 15 },
  "PATANJALI": { yahoo: "PATANJALI.NS", lot: 900 },
  "PAYTM": { yahoo: "PAYTM.NS", lot: 725 },
  "PERSISTENT": { yahoo: "PERSISTENT.NS", lot: 100 },
  "PETRONET": { yahoo: "PETRONET.NS", lot: 1800 },
  "PFC": { yahoo: "PFC.NS", lot: 1300 },
  "PGEL": { yahoo: "PGEL.NS", lot: 700 },
  "PHOENIXLTD": { yahoo: "PHOENIXLTD.NS", lot: 350 },
  "PIDILITIND": { yahoo: "PIDILITIND.NS", lot: 500 },
  "PIIND": { yahoo: "PIIND.NS", lot: 175 },
  "PNB": { yahoo: "PNB.NS", lot: 8000 },
  "PNBHOUSING": { yahoo: "PNBHOUSING.NS", lot: 650 },
  "POLICYBZR": { yahoo: "POLICYBZR.NS", lot: 350 },
  "POLYCAB": { yahoo: "POLYCAB.NS", lot: 125 },
  "POWERGRID": { yahoo: "POWERGRID.NS", lot: 1900 },
  "POWERINDIA": { yahoo: "POWERINDIA.NS", lot: 50 },
  "PPLPHARMA": { yahoo: "PPLPHARMA.NS", lot: 2500 },
  "PRESTIGE": { yahoo: "PRESTIGE.NS", lot: 450 },
  "RBLBANK": { yahoo: "RBLBANK.NS", lot: 3175 },
  "RECLTD": { yahoo: "RECLTD.NS", lot: 1275 },
  "RELIANCE": { yahoo: "RELIANCE.NS", lot: 500 },
  "RVNL": { yahoo: "RVNL.NS", lot: 1375 },
  "SAIL": { yahoo: "SAIL.NS", lot: 4700 },
  "SAMMAANCAP": { yahoo: "SAMMAANCAP.NS", lot: 4300 },
  "SBICARD": { yahoo: "SBICARD.NS", lot: 800 },
  "SBILIFE": { yahoo: "SBILIFE.NS", lot: 375 },
  "SBIN": { yahoo: "SBIN.NS", lot: 750 },
  "SHREECEM": { yahoo: "SHREECEM.NS", lot: 25 },
  "SHRIRAMFIN": { yahoo: "SHRIRAMFIN.NS", lot: 825 },
  "SIEMENS": { yahoo: "SIEMENS.NS", lot: 125 },
  "SOLARINDS": { yahoo: "SOLARINDS.NS", lot: 75 },
  "SONACOMS": { yahoo: "SONACOMS.NS", lot: 1050 },
  "SRF": { yahoo: "SRF.NS", lot: 200 },
  "SUNPHARMA": { yahoo: "SUNPHARMA.NS", lot: 350 },
  "SUPREMEIND": { yahoo: "SUPREMEIND.NS", lot: 175 },
  "SUZLON": { yahoo: "SUZLON.NS", lot: 8000 },
  "SYNGENE": { yahoo: "SYNGENE.NS", lot: 1000 },
  "TATACONSUM": { yahoo: "TATACONSUM.NS", lot: 550 },
  "TATAELXSI": { yahoo: "TATAELXSI.NS", lot: 100 },
  "TATAMOTORS": { yahoo: "TATAMOTORS.NS", lot: 800 },
  "TATAPOWER": { yahoo: "TATAPOWER.NS", lot: 1450 },
  "TATASTEEL": { yahoo: "TATASTEEL.NS", lot: 5500 },
  "TATATECH": { yahoo: "TATATECH.NS", lot: 800 },
  "TCS": { yahoo: "TCS.NS", lot: 175 },
  "TECHM": { yahoo: "TECHM.NS", lot: 600 },
  "TIINDIA": { yahoo: "TIINDIA.NS", lot: 200 },
  "TITAGARH": { yahoo: "TITAGARH.NS", lot: 725 },
  "TITAN": { yahoo: "TITAN.NS", lot: 175 },
  "TORNTPHARM": { yahoo: "TORNTPHARM.NS", lot: 250 },
  "TORNTPOWER": { yahoo: "TORNTPOWER.NS", lot: 375 },
  "TRENT": { yahoo: "TRENT.NS", lot: 100 },
  "TVSMOTOR": { yahoo: "TVSMOTOR.NS", lot: 350 },
  "ULTRACEMCO": { yahoo: "ULTRACEMCO.NS", lot: 50 },
  "UNIONBANK": { yahoo: "UNIONBANK.NS", lot: 4425 },
  "UNITDSPR": { yahoo: "UNITDSPR.NS", lot: 400 },
  "UNOMINDA": { yahoo: "UNOMINDA.NS", lot: 550 },
  "UPL": { yahoo: "UPL.NS", lot: 1355 },
  "VBL": { yahoo: "VBL.NS", lot: 1025 },
  "VEDL": { yahoo: "VEDL.NS", lot: 1150 },
  "VOLTAS": { yahoo: "VOLTAS.NS", lot: 375 },
  "WIPRO": { yahoo: "WIPRO.NS", lot: 3000 },
  "YESBANK": { yahoo: "YESBANK.NS", lot: 31100 },
  "ZYDUSLIFE": { yahoo: "ZYDUSLIFE.NS", lot: 900 },
};

// All Yahoo symbols for batch fetch (max ~200 per Yahoo API call)
export function getAllYahooSymbols(): string[] {
  return [
    ...Object.values(FNO_INDICES).map(i => i.yahoo),
    ...Object.values(FNO_STOCKS).map(s => s.yahoo),
  ];
}

// Total count
export const TOTAL_FNO = Object.keys(FNO_STOCKS).length + Object.keys(FNO_INDICES).length;
// 209 stocks + 4 indices = 213
